## 도형 그리기

In [ ]:
# 빈 스케치북 만들기

In [17]:
import cv2
import numpy as np

#세로 480 가로 640 channel rgb 빛의 삼원색

img = np.zeros((480 , 640 , 3) , dtype = np.uint8)
#img[:] = (255, 5 ,3) #전체 #blue green red 순서대로
img.shape



(480, 640, 3)

In [8]:
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [16]:
cv2.imshow('img' , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img

## 일부 영역 색칠

In [18]:
img = np.zeros((480 , 640 , 3))

img[100:200 , 200: 300] = (255, 255, 255) #slicing 을 이용해서
cv2.imshow('img' , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 직선 그리기
직선의 종류 (line type)

1. cv2.LINE_4 : 4픽셀로
2. cv2.LINE_8 :조금더 부드러운
3. cv2.LINE_AA


In [21]:
img = np.zeros((480 , 640 , 3) , dtype  = np.uint8)

COLOR = (0 , 255 , 255)# 노란색
THICHNESS = 3 #두께

cv2.line(img , (50 , 100)  , (400 , 50) , COLOR , THICHNESS , cv2.LINE_8) #x , y좌표를 나타내는
cv2.imshow('img' , img)
cv2.waitKey(3000)
cv2.destroyAllWindows()

## 원

In [25]:
img = np.zeros((480 , 640 , 3) , dtype  = np.uint8)

COLOR = (255 , 255 , 0)# 노란색
THICHNESS = 3 #두께
RADIUS = 50
cv2.circle(img , (200 , 100) , RADIUS , COLOR , THICHNESS , cv2.LINE_AA)
cv2.circle(img , (200 , 200) , RADIUS , COLOR , cv2.FILLED , cv2.LINE_AA)
cv2.imshow('img' , img)
cv2.waitKey(3000)
cv2.destroyAllWindows()

## 사각형

In [27]:
img = np.zeros((480 , 640 , 3) , dtype  = np.uint8)

COLOR = (255 , 255 , 0)# 노란색
THICHNESS = 3 #두께

cv2.rectangle(img , (100 , 100) , (200 , 200) , COLOR , THICHNESS)
#그릴 위치 왼쪽 위 좌표 , 오른쪽 아래 좌표 , 색깔 , 두꼐 
cv2.imshow('img' , img)
cv2.waitKey(3000)
cv2.destroyAllWindows()

## 다각형

In [29]:
img = np.zeros((480 , 640 , 3) , dtype  = np.uint8)

COLOR = (0 , 255 , 0)# 노란색
THICHNESS = 3 #두께

pts1 = np.array([[100 , 100] , [200 , 100] , [100 , 200]])
                                #닫힌 여부 True , False
#polylines를 이용하면 다각형
#[리스트 안에 넣어서 점을]
cv2.polylines(img ,  [pts1] , False , COLOR , THICHNESS)
cv2.imshow('img' , img)
cv2.waitKey(3000)
cv2.destroyAllWindows()